[package]
name = "milito"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.18"
bincode = "1.3"
serde= "1.0"
lazy_static = "1.4"
# rand = {version = "0.8", feature = ["wasm-bindgen"]}
js-sys = "0.3"
